"$schema" = 'https://starship.rs/config-schema.json'
format = """
$character\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
> \
"""

[character]
format = '$symbol '
success_symbol = '[⋊>](bold green)'
error_symbol = '[⋊>](bold red)'

[directory]
truncation_length = 5

[username]
format = '[$user]($style)@'
style_root = 'red bold'
style_user = 'yellow bold'
show_always = false
disabled = false

[hostname]
ssh_only = true
trim_at = '.'
format = '[$hostname]($style) '
style = 'yellow bold'
disabled = false